// Local PWABuilder-style checklist audit (manifest + service worker + security + installability)
'use strict';
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const WEB = path.join(__dirname, '..', 'web');
let pass = 0, fail = 0;
const check = (ok, label, detail = '') => { ok ? pass++ : fail++; console.log((ok ? '  ✅ ' : '  ❌ ') + label + (detail ? ' — ' + detail : '')); };

console.log('MANIFEST');
const m = JSON.parse(fs.readFileSync(path.join(WEB, 'manifest.webmanifest'), 'utf8'));
check(!!m.name && m.name.length >= 4, 'name', m.name);
check(!!m.short_name && m.short_name.length <= 12, 'short_name', m.short_name);
check(!!m.start_url, 'start_url', m.start_url);
check(!!m.scope, 'scope', m.scope);
check(['standalone', 'fullscreen', 'minimal-ui'].includes(m.display), 'display', m.display);
check(!!m.background_color, 'background_color', m.background_color);
check(!!m.theme_color, 'theme_color', m.theme_color);
check(!!m.description && m.description.length > 40, 'description length', m.description.length + ' chars');
check(!!m.lang, 'lang', m.lang);
const sizes = m.icons.map(i => i.sizes);
check(sizes.includes('192x192'), 'icon 192x192 present');
check(sizes.includes('512x512'), 'icon 512x512 present');
check(m.icons.some(i => i.purpose === 'any' && i.sizes === '512x512'), '512 any purpose');
check(m.icons.some(i => i.purpose === 'maskable'), 'maskable icon present');
for (const i of m.icons) {
  const f = path.join(WEB, i.src);
  const exists = fs.existsSync(f);
  const dim = exists ? execSync(`identify -format "%wx%h" ${f}`).toString() : 'missing';
  check(exists && dim === i.sizes, 'icon file matches declared size', i.src + ' ' + dim);
}
check(Array.isArray(m.shortcuts) && m.shortcuts.length >= 2, 'shortcuts', (m.shortcuts || []).length + ' entries');
const shots = m.screenshots || [];
check(shots.length >= 2 && shots.some(x => x.form_factor === 'wide') && shots.some(x => x.form_factor === 'narrow'), 'store screenshots (wide + narrow)', shots.length + ' entries');
for (const s of shots) check(fs.existsSync(path.join(WEB, s.src)), 'screenshot file exists', s.src);
check(!!m.share_target && !!m.share_target.action && !!(m.share_target.params || {}).text, 'share_target declared', m.share_target && m.share_target.action);
check(Array.isArray(m.file_handlers) && m.file_handlers.length >= 1 && !!m.file_handlers[0].accept, 'file_handlers declared', (m.file_handlers || []).length + ' handler');
check(!!m.launch_handler, 'launch_handler declared', JSON.stringify(m.launch_handler));
const mainSrc = fs.readFileSync(path.join(WEB, 'js', 'main.js'), 'utf8');
check(mainSrc.includes('launchQueue.setConsumer'), 'launchQueue consumer wired in boot');
check(mainSrc.includes("q.get('share')"), 'share-param boot handler wired');

console.log('SERVICE WORKER');
const sw = fs.readFileSync(path.join(WEB, 'sw.js'), 'utf8');
check(sw.includes("addEventListener('install'"), 'install handler + precache');
check(sw.includes("addEventListener('activate'"), 'activate handler + cache cleanup');
check(sw.includes("addEventListener('fetch'"), 'fetch handler (offline capability)');
check(sw.includes("caches.match('/index.html')"), 'offline navigation fallback');
const main = fs.readFileSync(path.join(WEB, 'js', 'main.js'), 'utf8');
check(main.includes("serviceWorker.register('/sw.js')"), 'SW registration in app boot');
check(sw.includes("startsWith('/api/')"), 'API/auth calls excluded from SW cache');

console.log('SECURITY & INSTALLABILITY');
const html = fs.readFileSync(path.join(WEB, 'index.html'), 'utf8');
check(html.includes('name="theme-color"'), 'theme-color meta');
check(html.includes('name="viewport"'), 'viewport meta');
check(html.includes('rel="manifest"'), 'manifest linked');
check(!/src="http:|href="http:/.test(html), 'no mixed content in shell');
check(html.includes('fonts.googleapis.com/css2'), 'Google Fonts stylesheet linked');
check(html.includes('rel="preconnect" href="https://fonts.gstatic.com"'), 'font preconnects declared');
check(sw.includes('fonts.gstatic.com'), 'SW runtime-caches Google Fonts for offline');
console.log('  ℹ️  HTTPS: served over TLS in deployment (preview proxy + your domain)');


console.log('\nMANIFEST CAPABILITIES — PWABuilder ManifestAnalyzer mirror (46)');
const dimOf = (f) => { try { return execSync(`identify -format "%wx%h" "${f}"`).toString(); } catch { return 'missing'; } };
const existsSrc = (src) => !!src && fs.existsSync(path.join(WEB, src.replace(/^\//, '')));
const typeOk = (i) => (i.type || 'image/png') === 'image/png' && (i.src || '').endsWith('.png');
const sizeOk = (i) => existsSrc(i.src) && dimOf(path.join(WEB, i.src.replace(/^\//, ''))) === i.sizes;
const A = (v) => Array.isArray(v) ? v : [];
const S = (v, n = 1, allow) => typeof v === 'string' && v.length >= n && (!allow || allow.includes(v));
const mIcons = A(m.icons), mShots = A(m.screenshots), mScuts = A(m.shortcuts);
const mScutIcons = mScuts.flatMap(x => A(x.icons));
const caps = [];
const cap = (id, ok) => caps.push([id, !!ok]);
cap('HasManifest', true);
cap('Name', S(m.name));
cap('Description', S(m.description));
cap('ThemeColor', S(m.theme_color, 3));
cap('BackgroundColor', S(m.background_color, 3));
cap('Shortcuts', mScuts.length > 0 && mScuts.some(x => S(x.name)) && mScuts.some(x => S(x.url)));
cap('ShortcutIconsAreFetchable', mScutIcons.length > 0 && mScutIcons.every(i => existsSrc(i.src)));
cap('ShortcutIconTypesAreValid', mScutIcons.every(i => typeOk(i)));
cap('ShortcutIconSizesAreValid', mScutIcons.every(i => sizeOk(i)));
cap('Categories', A(m.categories).some(c => S(c)));
cap('Icons', mIcons.length > 0 && mIcons.some(i => S(i.src)));
cap('IconsAreFetchable', mIcons.every(i => existsSrc(i.src)));
cap('IconTypesAreValid', mIcons.every(i => typeOk(i)));
cap('IconSizesAreValid', mIcons.every(i => sizeOk(i)));
cap('IconTypesAreNotIcos', mIcons.every(i => !(i.src || '').endsWith('.ico')));
cap('ImagesAreNotBase64Encoded', [...mIcons, ...mShots, ...mScutIcons].every(i => !(i.src || '').startsWith('data:')));
const sqAny = (n) => mIcons.some(i => (i.sizes || '').split(' ').includes(n + 'x' + n) && (!i.purpose || i.purpose.split(' ').includes('any')) && i.type === 'image/png' && (i.src || '').endsWith('.png'));
cap('HasSquare192x192PngAnyPurposeIcon', sqAny(192));
cap('HasSquare512x512PngAnyPurposeIcon', sqAny(512));
cap('Screenshots', mShots.length > 0 && mShots.some(x => S(x.src)));
cap('ScreenshotsAreFetchable', mShots.every(x => existsSrc(x.src)));
cap('ScreenshotTypesAreValid', mShots.every(x => typeOk(x)));
cap('ScreenshotSizesAreValid', mShots.every(x => sizeOk(x)));
cap('HasWideScreenshot', mShots.some(x => x.form_factor === 'wide'));
cap('HasNarrowScreenshot', mShots.some(x => x.form_factor === 'narrow'));
const fh = A(m.file_handlers);
cap('FileHandlers', fh.length > 0 && fh.some(x => S(x.action)) && fh.some(x => x.accept && typeof x.accept === 'object'));
const lh = m.launch_handler;
cap('LaunchHandler', !!lh && typeof lh === 'object' && (S(lh.client_mode) || A(lh.client_mode).some(c => S(c))));
cap('PreferRelatedApplication', typeof m.prefer_related_applications === 'boolean');
const ph = A(m.protocol_handlers);
cap('ProtocolHandlers', ph.length > 0 && ph.some(x => S(x.protocol)) && ph.some(x => S(x.url)));
const ra = A(m.related_applications);
cap('RelatedApplications', ra.length > 0 && ra.every(a => S(a.platform) && (S(a.url) || S(a.id))));
cap('ShareTarget', !!m.share_target && typeof m.share_target === 'object' && S(m.share_target.action));
cap('IarcRatingId', S(m.iarc_rating_id, 36));
const wz = A(m.widgets);
cap('Widgets', wz.length > 0 && wz.every(x => S(x.name) && S(x.description) && S(x.tag) && S(x.ms_ac_template) && A(x.screenshots).length > 0 && A(x.screenshots).every(sc => S(sc.src) && S(sc.sizes) && S(sc.label))));
cap('EdgeSidePanel', !!m.edge_side_panel && typeof m.edge_side_panel === 'object' && typeof m.edge_side_panel.preferred_width === 'number');
const dso = A(m.display_override);
cap('DisplayOverride', dso.some(o => S(o)));
cap('WindowControlsOverlay', dso.includes('window-controls-overlay'));
cap('TabbedDisplay', dso.includes('tabbed') && !!m.tab_strip && typeof m.tab_strip === 'object');
cap('NoteTaking', !!m.note_taking && typeof m.note_taking === 'object' && S(m.note_taking.new_note_url));
cap('Scope', S(m.scope, 1));
cap('ShortName', S(m.short_name, 1));
cap('StartUrl', S(m.start_url, 1));
cap('Display', S(m.display, 1, ['fullscreen', 'standalone', 'minimal-ui', 'browser', 'tabbed', 'window-controls-overlay']));
cap('Orientation', S(m.orientation, 1, ['any', 'natural', 'landscape', 'landscape-primary', 'landscape-secondary', 'portrait', 'portrait-primary', 'portrait-secondary']));
cap('Language', S(m.lang, 2));
cap('Direction', S(m.dir, 3, ['ltr', 'rtl', 'auto']));
const se = A(m.scope_extensions);
cap('ScopeExtensions', se.length > 0 && se.every(e => S(e.type) && S(e.origin) && /^https?:\/\//.test(e.origin)));
cap('Id', S(m.id, 1));
const capPass = caps.filter(c => c[1]).length;
for (const [id, ok] of caps) console.log(`  ${ok ? '✅' : '❌'} ${id}`);
console.log(`MANIFEST CAPABILITIES: ${capPass}/46` + (capPass < 46 ? ' — outstanding: ' + caps.filter(c => !c[1]).map(c => c[0]).join(', ') : ' — full house'));

console.log(`\nRESULT: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
